vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        profil_images:
            uri_prefix: images/photo
            upload_destination: '%kernel.project_dir%/public/images/photo'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
